baseURL = 'https://run-at-website.vercel.app/'
languageCode = 'en-us'
title = 'RunAt'
theme = 'github-style'

[params]
    favicon = "/images/github-mark.png"
    avatar = "/images/avatar.png"
    headerIcon = "/images/github-mark-white.png"
    enableSearch = true
    lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[outputs]
    home = ["HTML", "RSS", "JSON"]
